name: MPEX
version: '1.0'
main: io.github.closeddev.mpex.MPEX
api-version: '1.21'
commands:
  test:
    description: Hello world
    usage: /<command>
  game:
    description: Management Games
    usage: /<command>